### ISSUE TITLE
Uncaught SyntaxError: Unexpected token : in JSON at position 9

### ISSUE THREAD

**Issue by philoSurfer** [danieltrost/json-sort#3]
[Enter steps to reproduce:]

1. selected the following nested block of code in a json file:
```
"patches": {
            "drupal/color_field": {
                "color_field: contextual links": "https://www.drupal.org/files/issues/2018-08-21/issues-2994006-02.patch"
            },

            "drupal/features": {
                "system.theme.yml patch": "https://www.drupal.org/files/issues/2018-10-26/features_profile_conf_override_support-2668562-21.patch"
            },
            "drupal/foundation_layouts": {
                "off-canvas thumbnail image fix": "https://www.drupal.org/files/issues/2019-03-06/3037557-off-canvas-image-size_0.patch",
                "X-Y grid twig updates": "https://www.drupal.org/files/issues/2019-03-07/foundation_layout_X-Y_grid-2929021_0.patch"
            },
            "drupal/core": {
                "Support third party settings for components within a section": "https://www.drupal.org/files/issues/2019-02-26/3015152-tps-5.patch",
                "time picker polyfill issue": "https://www.drupal.org/files/issues/2019-02-04/2791693-33.patch"
            },
            "drupal/site_settings":{
                "dynamic permissions": "https://www.drupal.org/files/issues/2018-08-21/issues-2994003-02.patch"
            },
            "drupal/zurb_foundation": {
                "dependencies update": "https://www.drupal.org/files/issues/2019-02-13/foundation-dependencies-updates-3029876.patch"
            },
            "drupal/link_attributes": {
                "dependencies update": "patches/removing_link_attribute_wrapper.patch"
            }
        }
```
2. bork.

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: [json-sort](https://github.com/danieltrost/json-sort) package 1.3.0

### Stack Trace

Uncaught SyntaxError: Unexpected token : in JSON at position 9

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected token : in JSON at position 9
    at JSON.parse (<anonymous>)
    at Object.sort (/packages/json-sort/lib/json-sort.js:75:41)
    at HTMLElement.jsonSortSort (/packages/json-sort/lib/json-sort.js:24:36)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349922)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:677666)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:842467)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:837346)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349922)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1214917)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1211051)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:285128)
```

### Commands

```
     -1:08.1.0 core:backspace (input.hidden-input)
     -0:20.2.0 command-palette:toggle (input.hidden-input)
     -0:16.9.0 core:confirm (input.hidden-input)
     -0:16.9.0 json-sort:sort (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-debug-ui 1.0.4 
atom-ide-ui 0.13.0 
busy-signal 2.0.1 
color-picker 2.3.0 
git-time-machine 2.1.0 
ide-css 0.3.2 
ide-php 0.7.18 
ide-yaml 0.5.0 
intentions 1.1.5 
json-sort 1.3.0 
language-lua 0.9.11 
language-nginx 0.8.0 
linter 2.3.0 
linter-jsonlint 1.4.0 
linter-scss-lint 3.2.1 
linter-ui-default 1.7.1 
php-debug 0.3.5 
php-twig 4.0.0 
pigments 0.40.2 
platformio-ide-terminal 2.9.1 
sort-lines 0.19.0 
split-diff 1.6.0 
structure-view 0.2.1 
utf16offset 0.1.0 
```

**Comment by danieltrost** [comment]
Please select the object starting after `"patches":` in order to sort. The package has also been updated. Please confirm that this is working as intended and reopen if necessary.

**Comment by philoSurfer** [comment]
Works as intended. Thanks for the update. (sorry for the slow reply).  Rarely use github since Microsoft took over ;)
