### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by dinmiranda** [danieltrost/json-sort#4]
[Enter steps to reproduce:]

1. Open a json file.
2. Right click anywhere on the editor and select json-sort.

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Ubuntu 19.04
**Thrown From**: [json-sort](https://github.com/danieltrost/json-sort) package 1.3.0

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///snap/atom/227/usr/share/atom/resources/app.asar/static/index.html:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.sort (/packages/json-sort/lib/json-sort.js:75:41)
    at HTMLElement.jsonSortSort (/packages/json-sort/lib/json-sort.js:24:36)
    at CommandRegistry.handleCommandEvent (/snap/atom/227/usr/share/atom/resources/app/static/<embedded>:11:349960)
    at CommandRegistry.dispatch (/snap/atom/227/usr/share/atom/resources/app/static/<embedded>:11:348435)
    at AtomEnvironment.dispatchContextMenuCommand (/snap/atom/227/usr/share/atom/resources/app/static/<embedded>:1:716241)
    at EventEmitter.t (/snap/atom/227/usr/share/atom/resources/app/static/<embedded>:1:724247)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -6:03.7.0 application:open-file (atom-pane.pane.active)
     -5:20.7.0 atom-meld:diff-from-tab-tab (div.title)
  2x -4:55.9.0 split-diff:enable (div.title)
     -3:49.2.0 settings-view:open (input.hidden-input)
     -0:38.5.0 json-sort:sort (div.line)
```

### Non-Core Packages

```
atom-ide-debugger-node 0.7.3 
atom-ide-debugger-python 0.7.3 
atom-js-console 1.2.2 
atom-meld 0.3.5 
autocomplete-json 5.5.2 
autocomplete-modules 2.3.0 
bottom-dock 0.4.4 
build-grunt 0.4.0 
build-npm-apm 0.12.0 
eclipse-keybindings 0.9.0 
format-standard 4.3.0 
git-blame 1.8.0 
git-plus 8.6.3 
git-time-machine 2.1.0 
grunt-manager 0.1.16 
grunt-runner 0.14.0 
ide-json 0.2.1 
js-refactor 0.8.1 
jsformat 0.9.3 
json-sort 1.3.0 
npm 2.0.0 
npm-install 4.0.4 
npm-plus 0.4.0 
platformio-ide-terminal 2.9.1 
pretty-json 2.1.2 
split-diff 1.6.0 
xatom-debug 1.6.11 
xatom-debug-nodejs 0.9.3 
xml-formatter 0.13.0 
```

**Comment by danieltrost** [comment]
Please test on version `1.6.0` and confirm if this is still an issue. Remember to select an object only. For example:

Invalid:
```js
"someObject": {
  ...
}
```

Valid:
```js
{
  ...
}
```
