### ISSUE TITLE
Uncaught SyntaxError: Unexpected token I in JSON at position 0

### ISSUE THREAD

**Issue by jcervas** [danieltrost/json-sort#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.15
**Thrown From**: [json-sort](https://github.com/danieltrost/json-sort) package 1.6.0

### Stack Trace

Uncaught SyntaxError: Unexpected token I in JSON at position 0

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected token I in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.sort (/packages/json-sort/lib/json-sort.js:75:41)
    at HTMLElement.jsonSortSort (/packages/json-sort/lib/json-sort.js:24:36)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349123)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:347598)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:718718)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:726641)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -0:26.7.0 find-and-replace:show (input.hidden-input)
  9x -0:25.8.0 core:confirm (input.hidden-input)
     -0:07.1.0 json-sort:sort (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-csv-markdown 1.0.2 
atom-latex 0.8.11 
d3-snippets 1.2.1 
jekyll 2.1.0 
json-sort 1.6.0 
pp-markdown 0.0.2 
puddletown-d3-snippets 1.0.1 
r-exec 0.5.0 
rbox 0.5.0 
```

**Comment by gastrodon** [comment]
> Unexpected token I in JSON at position 0

This sounds like a problem with your JSON. Can you post a sample?
